### ISSUE TITLE
BUG found in abcore The application crashes when downloading is complete

### ISSUE THREAD

**Issue by facebook-786** [greenaddress/abcore#77]
# Project Information

* Repository: https://github.com/greenaddress/abcore
* Project Name:  abcore

# Expected behavior

I was expecting that when the file is completely downloaded, it will begin to appear in all the data available in the application and the application should not crash after the download is completed.

# Actual behavior

The app crashes as soon as I start downloading and when the download is complete

# How to reproduce

1-[Download ](https://github.com/greenaddress/abcore/releases) the application
2- Open the application and click Start download
3- Wait until the download is completed
4- see the bug 

* Browser/App version:  v0.73
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190513_015235](https://user-images.githubusercontent.com/50115498/57587777-8d514580-74bf-11e9-8d67-159226cd91fa.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(26936): FATAL EXCEPTION: IntentService[com.greenaddress.abcore.DownloadInstallCoreIntentService]

E/AndroidRuntime(26936): Process: com.greenaddress.abcore, PID: 26936

E/AndroidRuntime(26936): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference

E/AndroidRuntime(26936): 	at com.greenaddress.abcore.DownloadInstallCoreIntentService.a()

E/AndroidRuntime(26936): 	at com.greenaddress.abcore.DownloadInstallCoreIntentService.onHandleIntent()

E/AndroidRuntime(26936): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)

E/AndroidRuntime(26936): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(26936): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(26936): 	at android.os.HandlerThread.run(HandlerThread.java:61)
</code></pre>

**Comment by facebook-786** [comment]
hello sir @greenaddress  please review my contribution

**Comment by greenaddress** [comment]
@saraji-ali this should be fixed in the latest release!
