### ISSUE TITLE
[ABCore] Version 0.74 from F-Droid with core v0.18.1 crashes with listenonion=0

### ISSUE THREAD

**Issue by AreYouLoco** [greenaddress/abcore#96]
Hi,

I tried to manually set listenonion=0 in ABCore's bitcoin.conf but when I try to launch service app crashes.

I suspect it might be related to the qr code generation of onion node.

Will try to post logcat dump if I manage to reproduce...

Running AOKP 7.1.2

**Comment by AreYouLoco** [comment]
Steps to reproduce:
*start service with listenonion=0

Crash dump:
 --------- beginning of crash                                                                              09-29 11:14:41.839 15589 15589 E AndroidRuntime: FATAL EXCEPTION: main
09-29 11:14:41.839 15589 15589 E AndroidRuntime: Process: com.greenaddress.abcore, PID: 15589             09-29 11:14:41.839 15589 15589 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.greenaddress.intent.action.RPC_PROCESSED cat=[android.intent.category.DEFAULT] flg=0x10 (has extras) } in com.greenaddress.abcore.MainActivity$d@5366815                                              09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)                                                                                                      09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                                      09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)        09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6236)                                                                                                09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method) 09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)                                                                          09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)                                                                                          09-29 11:14:41.839 15589 15589 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference                             09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at c.b.b.c.b.c.a(:5)                              09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at com.greenaddress.abcore.MainActivity$d.onReceive(:10)                                                                                                    09-29 11:14:41.839 15589 15589 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)                                                                                   09-29 11:14:41.839 15589 15589 E AndroidRuntime:        ... 8 more
09-29 11:14:42.641 15589 15686 V c.c.a.d : 2019-09-29T09:14:42Z UpdateTip: new best=0000000000000000027279977cea96fe7661373f7c00004a5aa1af83d7a3f1a1 height=420573 version=0x20000000 log2_work=84.981591 tx=142179588 date='2016-07-13T15:27:39Z' progress=0.312389 cache=17.4MiB(129330txo)`

**Comment by AreYouLoco** [comment]
Also I noticed that when I switch the trigger to start service and move quicly to another app it seems to work fine and logcat says it is moving forward with blocks. But when I switch back to main window where there is qr code and address of the onion instance THEN it crashes immediately.

**Comment by AreYouLoco** [comment]
https://github.com/greenaddress/abcore/pull/69 Is this a possible fix?
